#!/bin/bash

set -e

if [[ -n "${DEMOS_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Generate front-end assets for demos that require build processes.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        yarn install
        yarn build

        # If new front-end assets exist.
        if [ -d "${DIR}/../dist" ]; then
        	# Clean the existing front-end assets.
        	rm -rf "${DIR}/../../../_phila-curb-map"
        fi
        
        # Allow Jekyll to serve the new front-end assets.
		mv "${DIR}/../dist" "${DIR}/../../../_phila-curb-map"
    fi
fi
